name: Sedge

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Download Sedge sources
        run: |
          echo "Downloading sedge sources..."
          curl -L https://github.com/NethermindEth/sedge/releases/download/v1.2.0/sedge-v1.2.0-linux-amd64 --output sedge
          chmod +x sedge
          ./sedge --help
          echo "Sources downloaded."

      - name: Run Sedge tool
        run: |
          echo 'Running sedge...'
          ./sedge generate full-node --logging none --no-mev-boost --no-validator --network chiado \
          -c lighthouse -e nethermind \
          --checkpoint-sync-url=http://139.144.26.89:4000/
          ./sedge run

      - name: Verify client synchronization
        run: |
          JSON_RPC_URL="http://139.144.26.89:4000"
          response=$(curl --data '{"method":"eth_syncing","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST $JSON_RPC_URL)
          if echo "$response" | grep -q '"result":false'; then
            echo "Syncing completed"
          else
            echo "Syncing in progress"
          fi

      - name: Run tests
        run: |
            echo $PWD
            cd ./test-ethereum-client
            pytest


      # - name: Run tests
      #   run: |
      #     JSON_RPC_URL="http://139.144.26.89:8545"
      #     response=$(curl --data '{"method":"eth_getBlockByNumber","params":[4491735, true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST $JSON_RPC_URL)
      #     echo "$response"
